services:
  - type: web
    name: QuickReels
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
